debug: false

bStats: true

max-thirstValue: 20.0

aridity:
  max-value: 4.0
  per-thirst: 1.0
  actions:
    swimming: 0.01
    break-block: 0.005
    sprinting: 0.1
    jumping: 0.05
    jumping-when-sprinting: 0.2
    attack-entity: 0.1

environment:
  formula: "0.5 + (%airTemp% + 50) / 100 * (3 - 0.5) * (1 - %humidity%)"

effect:
  disable-satiated: 6.0
  disable-jumping: 2.0

mmoitems:
  stats:
    water-purity:
      name: "水质纯净度"
      material: WATER_BUCKET
      lore:
        - "消耗品中水质的纯净度"
      types:
        - "all"
    water-keep:
      name: "保水性"
      material: LEATHER_CHESTPLATE
      lore:
        - "一件护甲可以减缓水分失去速度的能力"
      types:
        - "all"
  purity:
    dirty: 5.0
    raw: 7.0
    pure: 10.0

version: 1
