name: RealThirst
version: '${version}'
main: cn.encmys.ykdz.forest.realthirst.RealThirst
api-version: '1.16'
author: YK_DZ
folia-supported: false
softdepend:
  - RealisticSeasons
  - PlaceholderAPI
  - MMOItems